services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./romulus:/var/jenkins_home/workspace/romulus
      - ./jenkins_ssh:/var/jenkins_home/.ssh
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y python3 python3-pip python3-venv python3-full curl wget git openssh-client qemu-system-arm &&
        
        mkdir -p /var/jenkins_home/.ssh &&
        chmod 700 /var/jenkins_home/.ssh &&
        
        if [ -f /var/jenkins_home/.ssh/id_ed25519 ]; then
          chmod 600 /var/jenkins_home/.ssh/id_ed25519 &&
          chmod 644 /var/jenkins_home/.ssh/id_ed25519.pub
        fi &&
        
        ssh-keyscan -t ed25519 git.csc.sibsutis.ru >> /var/jenkins_home/.ssh/known_hosts 2>/dev/null &&
        ssh-keyscan -t rsa git.csc.sibsutis.ru >> /var/jenkins_home/.ssh/known_hosts 2>/dev/null &&
        chmod 644 /var/jenkins_home/.ssh/known_hosts &&
        
        chown -R jenkins:jenkins /var/jenkins_home/.ssh &&
        
        /usr/local/bin/jenkins.sh
      "

  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""

volumes:
  jenkins_home:
